name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: npm i && npx vuepress build

    - name: Deploy VuePress website to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: .vuepress/dist
        fqdn: open-election-compass.com
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
